[project]
name = "aurabot"
version = "0.1.0"
description = "A bot that senses the aura of the market."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pump-bot",
]

[tool.uv.sources]
pump-bot = { path = "../pumpfun-bonkfun-bot", editable = true }
